name: dart_code_coverage
description: A package with helpers for generating and editing code coverage reports in dart.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/defuncart/dart_code_coverage

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
