name: dart_code_coverage
description: A package with helpers for generating and editing code coverage reports in dart.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/defuncart/dart_code_coverage
repository: https://github.com/defuncart/dart_code_coverage
issue_tracker: https://github.com/defuncart/dart_code_coverage/issues

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  args: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
